"""initial_schema

Revision ID: 489998fbd6b1
Revises: 
Create Date: 2026-09-29 09:55:50.954272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489998fbd6b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(password_hash) >= 20', name='chk_admins_password_len'),
    sa.CheckConstraint('length(username) >= 3', name='chk_admins_username_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('Factory', 'Machinery', 'Quality Testing', 'Finished Doors', 'General')", name='chk_gallery_category'),
    sa.CheckConstraint('length(image_path) > 0', name='chk_gallery_path_len'),
    sa.CheckConstraint('length(title) >= 2', name='chk_gallery_title_len'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gallery_images_category_active_order', 'gallery_images', ['category', 'is_active', 'sort_order'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(name) >= 2', name='chk_categories_name_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_product_categories_active_order', 'product_categories', ['is_active', 'sort_order'], unique=False)
    op.create_table('website_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(content) > 0', name='chk_content_body_len'),
    sa.CheckConstraint('length(title) > 0', name='chk_content_title_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_key')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('core_type', sa.String(length=50), nullable=False),
    sa.Column('dipping', sa.String(length=50), nullable=False),
    sa.Column('standard_thicknesses', sa.String(length=100), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('show_price', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("core_type IN ('Single Core', 'Double Core', 'Both')", name='chk_products_core_type'),
    sa.CheckConstraint("dipping IN ('With Dipping', 'Without Dipping', 'Both')", name='chk_products_dipping'),
    sa.CheckConstraint('base_price IS NULL OR base_price >= 0', name='chk_products_base_price'),
    sa.CheckConstraint('length(name) >= 2', name='chk_products_name_len'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_products_category_active_order', 'products', ['category_id', 'is_active', 'sort_order'], unique=False)
    op.create_index('ix_products_featured', 'products', ['is_featured', 'is_active', 'sort_order'], unique=False)
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_number', sa.String(length=30), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('door_type', sa.String(length=50), nullable=False),
    sa.Column('core_type', sa.String(length=50), nullable=False),
    sa.Column('dipping', sa.String(length=50), nullable=False),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('height_unit', sa.String(length=10), nullable=False),
    sa.Column('width', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('width_unit', sa.String(length=10), nullable=False),
    sa.Column('thickness_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("core_type IN ('Single Core', 'Double Core', 'Not Specified')", name='chk_enquiries_core_type'),
    sa.CheckConstraint("dipping IN ('With Dipping', 'Without Dipping', 'Not Specified')", name='chk_enquiries_dipping'),
    sa.CheckConstraint("height_unit IN ('ft', 'in', 'cm', 'm')", name='chk_enquiries_height_unit'),
    sa.CheckConstraint("status IN ('New', 'Contacted', 'Quoted', 'In Discussion', 'Closed', 'Archived')", name='chk_enquiries_status'),
    sa.CheckConstraint("width_unit IN ('ft', 'in', 'cm', 'm')", name='chk_enquiries_width_unit'),
    sa.CheckConstraint('height > 0', name='chk_enquiries_height_pos'),
    sa.CheckConstraint('length(customer_name) >= 2', name='chk_enquiries_name_len'),
    sa.CheckConstraint('length(door_type) > 0', name='chk_enquiries_door_type'),
    sa.CheckConstraint('length(phone) >= 7', name='chk_enquiries_phone_len'),
    sa.CheckConstraint('length(reference_number) >= 10', name='chk_enquiries_ref_len'),
    sa.CheckConstraint('quantity >= 1', name='chk_enquiries_qty_pos'),
    sa.CheckConstraint('thickness_mm > 0', name='chk_enquiries_thickness_pos'),
    sa.CheckConstraint('width > 0', name='chk_enquiries_width_pos'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index('ix_enquiries_phone', 'enquiries', ['phone'], unique=False)
    op.create_index('ix_enquiries_status_created', 'enquiries', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(image_path) > 0', name='chk_product_images_path_len'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_images_product_order', 'product_images', ['product_id', 'sort_order'], unique=False)
    op.create_index('uq_product_primary_image', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_primary = true'), sqlite_where=sa.text('is_primary = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_primary_image', table_name='product_images', postgresql_where=sa.text('is_primary = true'), sqlite_where=sa.text('is_primary = 1'))
    op.drop_index('ix_product_images_product_order', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_enquiries_status_created', table_name='enquiries')
    op.drop_index('ix_enquiries_phone', table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_index('ix_products_featured', table_name='products')
    op.drop_index('ix_products_category_active_order', table_name='products')
    op.drop_table('products')
    op.drop_table('website_contents')
    op.drop_index('ix_product_categories_active_order', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index('ix_gallery_images_category_active_order', table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_table('admins')
    # ### end Alembic commands ###
